//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BabyShop.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Komentar
    {
        public string Sadrzaj { get; set; }
        public Nullable<int> Ocena { get; set; }
        public int Komentar_ID { get; set; }
        public string Artikal_Naziv { get; set; }
        public string Kupac_Username { get; set; }
    
        public virtual Artikal Artikal { get; set; }
        public virtual Kupac Kupac { get; set; }
    }
}
