//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BabyShop.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vrsta
    {
        public int Vrsta_ID { get; set; }
        public string Naziv { get; set; }
        public string Opis { get; set; }
        public int Tip_ID { get; set; }
        public string Artikal_Naziv { get; set; }
    
        public virtual Tip Tip { get; set; }
    }
}
